setwd("/E/szkola/methylation/pliki_rda")

load("istotne_ucec.rda")
load("istotne_coad.rda")
load("istotne_brca.rda")
load("istotne_coadread.rda")
load("istotne_gbm.rda")
load("istotne_gbmlgg.rda")
load("istotne_kipan.rda")
load("istotne_kirc.rda")
load("istotne_kirp.rda")
load("istotne_laml.rda")
load("istotne_luad.rda")
load("istotne_stes.rda")
load("istotne_stad.rda")

coad = names(istotne_coad)
ucec = names(istotne_ucec)
brca = names(istotne_brca)
coadread = names(istotne_coadread)
gbm = names(istotne_gbm)
gmblgg = names(istotne_gbmlgg)
kipan = names(istotne_kipan)
kirc = names(istotne_kirc)
kirp = names(istotne_kirp)
laml = names(istotne_laml)
luad = names(istotne_luad)
stes = names(istotne_stes)
stad = names(istotne_stad)

all = c(coad,ucec,brca,coadread,gbm,gmblgg,kipan,kirc,kirp,laml,luad) 
all = sort(all)
r = rle(all)
r$values[which(r$lengths>3)]
r$values[which(r$lengths>4)]

